/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2014-10-06 04:50:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MP3BBS_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1411796064000L));
    _jspx_dependants.put("jar:file:/C:/Development/Github/140908_Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Day1001mini/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>한잔해의 MP3 게시판</title>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>\r\n");
      out.write("        <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Ionicons -->\r\n");
      out.write("        <link href=\"//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Theme style -->\r\n");
      out.write("        <link href=\"../css/AdminLTE.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("          <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("          <script src=\"https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("    </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<body class=\"skin-blue\">\r\n");
      out.write("        <!-- header logo: style can be found in header.less -->\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <a href=\"/main\" class=\"logo\">\r\n");
      out.write("                <!-- Add the class icon to your logo image or logo icon to add the margining -->\r\n");
      out.write("                Bit 58th\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- Header Navbar: style can be found in header.less -->\r\n");
      out.write("            <nav class=\"navbar navbar-static-top\" role=\"navigation\">\r\n");
      out.write("                <!-- Sidebar toggle button-->\r\n");
      out.write("                <a href=\"#\" class=\"navbar-btn sidebar-toggle\" data-toggle=\"offcanvas\" role=\"button\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"navbar-right\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav\">\r\n");
      out.write("                        <!-- Messages: style can be found in dropdown.less-->\r\n");
      out.write("                        <li class=\"dropdown messages-menu\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("                                <span class=\"label label-success\">4</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li class=\"header\">You have 4 messages</li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <!-- inner menu: contains the actual data -->\r\n");
      out.write("                                    <ul class=\"menu\">\r\n");
      out.write("                                        <li><!-- start message -->\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <div class=\"pull-left\">\r\n");
      out.write("                                                    <img src=\"img/avatar3.png\" class=\"img-circle\" alt=\"User Image\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <h4>\r\n");
      out.write("                                                    Support Team\r\n");
      out.write("                                                    <small><i class=\"fa fa-clock-o\"></i> 5 mins</small>\r\n");
      out.write("                                                </h4>\r\n");
      out.write("                                                <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li><!-- end message -->\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <div class=\"pull-left\">\r\n");
      out.write("                                                    <img src=\"img/avatar2.png\" class=\"img-circle\" alt=\"user image\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <h4>\r\n");
      out.write("                                                    AdminLTE Design Team\r\n");
      out.write("                                                    <small><i class=\"fa fa-clock-o\"></i> 2 hours</small>\r\n");
      out.write("                                                </h4>\r\n");
      out.write("                                                <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <div class=\"pull-left\">\r\n");
      out.write("                                                    <img src=\"img/avatar.png\" class=\"img-circle\" alt=\"user image\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <h4>\r\n");
      out.write("                                                    Developers\r\n");
      out.write("                                                    <small><i class=\"fa fa-clock-o\"></i> Today</small>\r\n");
      out.write("                                                </h4>\r\n");
      out.write("                                                <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <div class=\"pull-left\">\r\n");
      out.write("                                                    <img src=\"img/avatar2.png\" class=\"img-circle\" alt=\"user image\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <h4>\r\n");
      out.write("                                                    Sales Department\r\n");
      out.write("                                                    <small><i class=\"fa fa-clock-o\"></i> Yesterday</small>\r\n");
      out.write("                                                </h4>\r\n");
      out.write("                                                <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <div class=\"pull-left\">\r\n");
      out.write("                                                    <img src=\"img/avatar.png\" class=\"img-circle\" alt=\"user image\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <h4>\r\n");
      out.write("                                                    Reviewers\r\n");
      out.write("                                                    <small><i class=\"fa fa-clock-o\"></i> 2 days</small>\r\n");
      out.write("                                                </h4>\r\n");
      out.write("                                                <p>Why not buy a new awesome theme?</p>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"footer\"><a href=\"#\">See All Messages</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- Notifications: style can be found in dropdown.less -->\r\n");
      out.write("                        <li class=\"dropdown notifications-menu\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"fa fa-warning\"></i>\r\n");
      out.write("                                <span class=\"label label-warning\">10</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li class=\"header\">You have 10 notifications</li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <!-- inner menu: contains the actual data -->\r\n");
      out.write("                                    <ul class=\"menu\">\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"ion ion-ios7-people info\"></i> 5 new members joined today\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"fa fa-warning danger\"></i> Very long description here that may not fit into the page and may cause design problems\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"fa fa-users warning\"></i> 5 new members joined\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"ion ion-ios7-cart success\"></i> 25 sales made\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                        <li>\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <i class=\"ion ion-ios7-person danger\"></i> You changed your username\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"footer\"><a href=\"#\">View all</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- Tasks: style can be found in dropdown.less -->\r\n");
      out.write("                        <li class=\"dropdown tasks-menu\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"fa fa-tasks\"></i>\r\n");
      out.write("                                <span class=\"label label-danger\">9</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li class=\"header\">You have 9 tasks</li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <!-- inner menu: contains the actual data -->\r\n");
      out.write("                                    <ul class=\"menu\">\r\n");
      out.write("                                        <li><!-- Task item -->\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <h3>\r\n");
      out.write("                                                    Design some buttons\r\n");
      out.write("                                                    <small class=\"pull-right\">20%</small>\r\n");
      out.write("                                                </h3>\r\n");
      out.write("                                                <div class=\"progress xs\">\r\n");
      out.write("                                                    <div class=\"progress-bar progress-bar-aqua\" style=\"width: 20%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                                                        <span class=\"sr-only\">20% Complete</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li><!-- end task item -->\r\n");
      out.write("                                        <li><!-- Task item -->\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <h3>\r\n");
      out.write("                                                    Create a nice theme\r\n");
      out.write("                                                    <small class=\"pull-right\">40%</small>\r\n");
      out.write("                                                </h3>\r\n");
      out.write("                                                <div class=\"progress xs\">\r\n");
      out.write("                                                    <div class=\"progress-bar progress-bar-green\" style=\"width: 40%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                                                        <span class=\"sr-only\">40% Complete</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li><!-- end task item -->\r\n");
      out.write("                                        <li><!-- Task item -->\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <h3>\r\n");
      out.write("                                                    Some task I need to do\r\n");
      out.write("                                                    <small class=\"pull-right\">60%</small>\r\n");
      out.write("                                                </h3>\r\n");
      out.write("                                                <div class=\"progress xs\">\r\n");
      out.write("                                                    <div class=\"progress-bar progress-bar-red\" style=\"width: 60%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                                                        <span class=\"sr-only\">60% Complete</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li><!-- end task item -->\r\n");
      out.write("                                        <li><!-- Task item -->\r\n");
      out.write("                                            <a href=\"#\">\r\n");
      out.write("                                                <h3>\r\n");
      out.write("                                                    Make beautiful transitions\r\n");
      out.write("                                                    <small class=\"pull-right\">80%</small>\r\n");
      out.write("                                                </h3>\r\n");
      out.write("                                                <div class=\"progress xs\">\r\n");
      out.write("                                                    <div class=\"progress-bar progress-bar-yellow\" style=\"width: 80%\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\">\r\n");
      out.write("                                                        <span class=\"sr-only\">80% Complete</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </li><!-- end task item -->\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"footer\">\r\n");
      out.write("                                    <a href=\"#\">View all tasks</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- User Account: style can be found in dropdown.less -->\r\n");
      out.write("                        <li class=\"dropdown user user-menu\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("                                <i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("                                <span>Jane Doe <i class=\"caret\"></i></span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <!-- User image -->\r\n");
      out.write("                                <li class=\"user-header bg-light-blue\">\r\n");
      out.write("                                    <img src=\"img/avatar3.png\" class=\"img-circle\" alt=\"User Image\" />\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        Jane Doe - Web Developer\r\n");
      out.write("                                        <small>Member since Nov. 2012</small>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <!-- Menu Body -->\r\n");
      out.write("                                <li class=\"user-body\">\r\n");
      out.write("                                    <div class=\"col-xs-4 text-center\">\r\n");
      out.write("                                        <a href=\"#\">Followers</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-xs-4 text-center\">\r\n");
      out.write("                                        <a href=\"#\">Sales</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-xs-4 text-center\">\r\n");
      out.write("                                        <a href=\"#\">Friends</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <!-- Menu Footer-->\r\n");
      out.write("                                <li class=\"user-footer\">\r\n");
      out.write("                                    <div class=\"pull-left\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-default btn-flat\">Profile</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"pull-right\">\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-default btn-flat\">Sign out</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <div class=\"wrapper row-offcanvas row-offcanvas-left\">\r\n");
      out.write("            <!-- Left side column. contains the logo and sidebar -->\r\n");
      out.write("            <aside class=\"left-side sidebar-offcanvas\">\r\n");
      out.write("                <!-- sidebar: style can be found in sidebar.less -->\r\n");
      out.write("                <section class=\"sidebar\">\r\n");
      out.write("                    <!-- Sidebar user panel -->\r\n");
      out.write("                    <div class=\"user-panel\">\r\n");
      out.write("                        <div class=\"pull-left info\">\r\n");
      out.write("                            <p> 로그인이 필요합니다. </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"pull-left info\">\r\n");
      out.write("                        <form action=\"../../index.html\" method=\"post\">\r\n");
      out.write("                <div class=\"body bg-gray\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"text\" name=\"userid\" class=\"form-control\" placeholder=\"User ID\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"password\" name=\"password\" class=\"form-control\" placeholder=\"Password\">\r\n");
      out.write("                    </div>          \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"remember_me\"> Remember me\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"footer\">                                                               \r\n");
      out.write("                    <button type=\"submit\" class=\"btn bg-olive btn-block\">Sign me in</button>  \r\n");
      out.write("                    \r\n");
      out.write("                    <p><a href=\"#\">I forgot my password</a></p>\r\n");
      out.write("                    \r\n");
      out.write("                    <a href=\"register.html\" class=\"text-center\">Register a new membership</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("                        \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- search form -->\r\n");
      out.write("                    <form action=\"#\" method=\"get\" class=\"sidebar-form\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"text\" name=\"q\" class=\"form-control\" placeholder=\"Search...\"/>\r\n");
      out.write("                            <span class=\"input-group-btn\">\r\n");
      out.write("                                <button type='submit' name='seach' id='search-btn' class=\"btn btn-flat\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("                            </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- /.search form -->\r\n");
      out.write("                    <!-- sidebar menu: : style can be found in sidebar.less -->\r\n");
      out.write("                    <ul class=\"sidebar-menu\">\r\n");
      out.write("                        <li class=\"active\">\r\n");
      out.write("                            <a href=\"/main\">\r\n");
      out.write("                                <i class=\"fa fa-dashboard\"></i> <span>메인 페이지</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"/upload\" data-toggle=\"modal\" data-target=\"#compose-modal\">\r\n");
      out.write("                                <i class=\"fa fa-th\"></i> <span>MP3 업로드</span> <small class=\"badge pull-right bg-green\">new</small>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </section>\r\n");
      out.write("                <!-- /.sidebar -->\r\n");
      out.write("            </aside>\r\n");
      out.write("\r\n");
      out.write("            <!-- Right side column. Contains the navbar and content of the page -->\r\n");
      out.write("            <aside class=\"right-side\">\r\n");
      out.write("                <!-- Content Header (Page header) -->\r\n");
      out.write("                <section class=\"content-header\">\r\n");
      out.write("                    <h1>\r\n");
      out.write("                        한잔해의 MP3 게시판\r\n");
      out.write("                        <small>Control panel</small>\r\n");
      out.write("                    </h1>\r\n");
      out.write("                    <ol class=\"breadcrumb\">\r\n");
      out.write("                        <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> Home</a></li>\r\n");
      out.write("                        <li class=\"active\">Dashboard</li>\r\n");
      out.write("                    </ol>\r\n");
      out.write("                </section>\r\n");
      out.write("\r\n");
      out.write("                <!-- Main content -->\r\n");
      out.write("\t<section class=\"content\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                                    </div><!-- /.row -->                                                                        \r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div><!-- /.box -->                            \r\n");
      out.write("\r\n");
      out.write("                        </section><!-- right col -->\r\n");
      out.write("                    </div><!-- /.row (main row) -->\r\n");
      out.write("\r\n");
      out.write("                </section><!-- /.content -->\r\n");
      out.write("            </aside><!-- /.right-side -->\r\n");
      out.write("        </div><!-- ./wrapper -->\r\n");
      out.write("\r\n");
      out.write("        <!-- add new calendar event modal -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script src=\"//code.jquery.com/ui/1.11.1/jquery-ui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- Morris.js charts -->\r\n");
      out.write("        <script src=\"//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js\"></script>\r\n");
      out.write("        <script src=\"js/plugins/morris/morris.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- Sparkline -->\r\n");
      out.write("        <script src=\"js/plugins/sparkline/jquery.sparkline.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- jvectormap -->\r\n");
      out.write("        <script src=\"js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script src=\"js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- jQuery Knob Chart -->\r\n");
      out.write("        <script src=\"js/plugins/jqueryKnob/jquery.knob.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- daterangepicker -->\r\n");
      out.write("        <script src=\"js/plugins/daterangepicker/daterangepicker.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- datepicker -->\r\n");
      out.write("        <script src=\"js/plugins/datepicker/bootstrap-datepicker.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- Bootstrap WYSIHTML5 -->\r\n");
      out.write("        <script src=\"js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <!-- iCheck -->\r\n");
      out.write("        <script src=\"js/plugins/iCheck/icheck.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- AdminLTE App -->\r\n");
      out.write("        <script src=\"js/AdminLTE/app.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- AdminLTE dashboard demo (This is only for demo purposes) -->\r\n");
      out.write("        <script src=\"js/AdminLTE/dashboard.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!-- AdminLTE for demo purposes -->\r\n");
      out.write("        <script src=\"js/AdminLTE/demo.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <!-- upload banner -->\r\n");
      out.write("        <div class=\"modal fade\" id=\"compose-modal\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                        <h4 class=\"modal-title\"><i class=\"fa fa-envelope-o\"></i> Compose New Message</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- upload body -->\r\n");
      out.write("                </div><!-- /.modal-content -->\r\n");
      out.write("            </div><!-- /.modal-dialog -->\r\n");
      out.write("        </div><!-- /.modal -->\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/jsp/MP3BBS.jsp(355,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("line");
    // /WEB-INF/jsp/MP3BBS.jsp(355,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${MP3List}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"col-lg-3 col-xs-6\" >\r\n");
          out.write("\t\t\t\t<!-- small box -->\r\n");
          out.write("\t\t\t\t<div class=\"small-box bg-aqua\" >\r\n");
          out.write("\t\t\t\t\t<div class=\"inner\" >\r\n");
          out.write("\t\t\t\t\t\t<h3><b><p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${line.getTitle()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p></b></h3>\r\n");
          out.write("\t\t\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${line.getArt()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("<br>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${line.getImg()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<!-- \r\n");
          out.write("\t\t\t\t\t<div class=\"icon\"><img src=\"image.jpg\" width=80 height=80>\r\n");
          out.write("\t\t\t\t\t\t<i class=\"ion\"></i>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t -->\r\n");
          out.write("\t\t\t\t\t<div class=\"icon\"><a href=\"/mp3Info?mno=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${line.getMno()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"><img src=\"image.jpg\" width=80 height=80></a>\r\n");
          out.write("\t\t\t\t\t\t<i class=\"ion\"></i>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t<a href=\"/mp3Info?mno=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${line.getMno()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"small-box-footer\"> More info <i\r\n");
          out.write("\t\t\t\t\t\tclass=\"fa fa-arrow-circle-right\"></i>\r\n");
          out.write("\t\t\t\t\t</a>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<!-- ./col -->\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
