/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2014-10-06 04:38:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class uploadPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1411796064000L));
    _jspx_dependants.put("jar:file:/C:/Development/Github/140908_Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Day1001mini/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"text-align:center\">\r\n");
      out.write("\t<h1>MP3 등록</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t<form action=\"upload\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t노래 제목 : <input type=\"text\" name=\"title\" placeholder=\"노래제목을 입력해주세요\"><br>\r\n");
      out.write("\t가수 : <input type=\"text\" name=\"art\" placeholder=\"가수이름을 입력해주세요\"><br>\r\n");
      out.write("\t앨범 : <input type=\"text\" name=\"alb\" placeholder=\"앨범을 입력해주세요\"><br>\r\n");
      out.write("\t장르 : <input type=\"text\" name=\"cate\" placeholder=\"장르를 입력해주세요\"><br>\r\n");
      out.write("\t노래 설명 : <input type=\"text\" name=\"desccont\" placeholder=\"노래설명을 입력해주세요\"><br>\r\n");
      out.write("\t작성자 : <input type=\"text\" name=\"userID\" placeholder=\"작성자를 입력해주세요\"><br>\r\n");
      out.write("\tmp3파일 : <input type=\"file\" name=\"mp3File\"><br>\r\n");
      out.write("\t<input type=\"reset\" name=\"초기화\">\r\n");
      out.write("\t<input type=\"submit\" value=\"등록하기\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t -->\r\n");
      out.write("\t<form action=\"upload\" method=\"post\"  enctype=\"multipart/form-data\">\r\n");
      out.write("                        <div class=\"modal-body\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-addon\">제목:</span>\r\n");
      out.write("                                    <input name=\"title\" type=\"text\" class=\"form-control\" placeholder=\"노래제목을 입력해주세요\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-addon\">가수:</span>\r\n");
      out.write("                                    <input name=\"art\" type=\"text\" class=\"form-control\" placeholder=\"가수이름을 입력해주세요\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-addon\">앨범:</span>\r\n");
      out.write("                                    <input name=alb\" type=\"text\" class=\"form-control\" placeholder=\"앨범을 입력해주세요\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-addon\">장르:</span>\r\n");
      out.write("                                    <input name=\"cate\" type=\"text\" class=\"form-control\" placeholder=\"장르를 입력해주세요\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-addon\">설명:</span>\r\n");
      out.write("                                    <input name=\"desccont\" type=\"text\" class=\"form-control\" placeholder=\"노래설명을 입력해주세요\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"input-group\">\r\n");
      out.write("                                    <span class=\"input-group-addon\">작성자:</span>\r\n");
      out.write("                                    <input name=\"userID\" type=\"text\" class=\"form-control\" placeholder=\"작성자 ID를 입력해주세요\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"btn btn-success btn-file\">\r\n");
      out.write("                                    <i class=\"fa fa-paperclip\"></i> MP3파일 등록\r\n");
      out.write("                                    <input type=\"file\" name=\"mp3File\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"help-block\">Max. 10MB</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"modal-footer clearfix\">\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\"><i class=\"fa fa-times\"></i>취소</button>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary pull-left\"><i class=\"fa fa-envelope\"></i>등록</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
